testproject/book/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', login_required(views.BookListView.as_view(), login_url='/login'), name='index'),
    # path('detail<slug:slug>/', views.detail, name='detail'),
    path('detail<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    re_path(r'add/$', views.book_add, name='book_add'),
    
    re_path(r'cart/add/(?P<slug>[\w-]+)/$', views.cart_add, name='cart_add'),
    re_path(r'cart/delete/(?P<slug>[\w-]+)/$', views.cart_delete, name='cart_delete'),
    re_path(r'cart/list/$', views.cart_list, name='cart_list'),
    re_path(r'cart/checkout/$', views.cart_checkout, name='cart_checkout'),
]
  

testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from book.api import router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
    path('book/', include(('book.urls', 'book'), namespace='book')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/book/models.py
from django.db import models
from django.utils.html import format_html


BOOK_LEVEL_CHOICE = {
    ('B', 'Basic'),
    ('I', 'Intermediate'),
    ('A', 'Advance'),
}


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Category'

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Author'

    def __str__(self):
        return self.name





class Book(models.Model):
    code = models.CharField(max_length=10, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField(default=0)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)
    author = models.ManyToManyField(Author, blank=True)
    level = models.CharField(max_length=5, null=True, blank=True, choices=BOOK_LEVEL_CHOICE)
    image = models.FileField(upload_to='upload', null=True, blank=True)
    published = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Book'

    def __str__(self):
        return self.name
    
    def show_image(self):
        if self.image: #if image have uploaded
            return format_html('<img src="' + self.image.url + '" height="50px"> ')
        return '' # else return blank
    show_image.allow_tags = True

    def get_comment_count(self):
        return self.bookcomment_set.count()


class BookComment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    rating = models.IntegerField(default=0)

    class Meta:
        ordering = ['id']
        verbose_name_plural = 'Book Comment'

    def __str__(self):
        return self.comment

testproject/book/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ['id', 'slug', 'published', 'created', 'updated']

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['code'].error_messages = {
            'required': 'Please enter book code !!',
        }    
        self.fields['name'].error_messages = {
            'required': 'Please enter book name..',
        }    
        self.fields['price'].error_messages = {
            'required': 'Please enter book price..',
            'invalid': 'Please enter a valid book price..',
        }   

    def clean(self):
        cleaned_data = super(BookForm, self).clean()
        if not cleaned_data.get('category'):
            self.add_error('category', 'Please select category name..')

        if not cleaned_data.get('author'):
            self.add_error('author', 'Please select author name..')

testproject/book/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.urls import reverse  #change name to be routing
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required

from .models import Category, Book
from .forms import BookForm
from slugify import slugify


@login_required
def index(request):
    categories = Category.objects.all()
    books = Book.objects.filter(published=True)


    categ_id =  request.GET.get('categoryid')
    if categ_id:
        # if category has value, then filtering
        books = books.filter(category_id=categ_id)

    paginator = Paginator(books, 2)
    page = request.GET.get('page')
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)


    return render(request, 'book/index.html', {
        'categories': categories,
        'books': books,
        'categ_id': categ_id,
    })

def detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    return render(request, 'book/detail.html', {
        'book': book,
    })

def book_add(request):
    form = BookForm()
    
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.slug = slugify(book.name)
            book.published = True
            book.save()
            form.save_m2m()
            messages.success(request, 'Save success')
            return HttpResponseRedirect(reverse('book:index', kwargs={}))
        messages.error(request, 'Save failed!')
    return render(request, 'book/add.html', {
        'form': form,
    })




class BookListView(ListView):
    model = Book
    template_name = 'book/index.html'
    context_object_name = 'books'
    paginate_by = 5 

    def get_queryset(self):
        return Book.objects.filter(published=True)

    def get_context_data(self, *args, **kwargs):
        cd = super(BookListView, self).get_context_data(*args, **kwargs)
        cd.update({
            'categories': Category.objects.all(),
        })
        return cd


class BookDetailView(DetailView):
    model = Book
    template_name = 'book/detail.html'
    slug_url_kwarg = 'slug'


def cart_add(request, slug):
    book = get_object_or_404(Book, slug=slug)
    cart_items = request.session.get('cart_items') or []

    # update exiting item
    duplicated = False
    for c in cart_items:
        if c.get('slug') == book.slug:
            c['qty'] =  int(c.get('qty') or '1') + 1
            duplicated = True

    # insert new item
    if not duplicated:
        cart_items.append({
            'id': book.id,
            'slug': book.slug,
            'name': book.name,
            'price': book.price,
            'qty': 1,
        })

    request.session['cart_items'] = cart_items
    return HttpResponseRedirect(reverse('book:cart_list', kwargs={}))


def cart_list(request):
    cart_items = request.session.get('cart_items') or []

    total_qty = 0
    for c in cart_items:
        total_qty = total_qty + c.get('qty')

    request.session['cart_qty'] = total_qty
    return render(request, 'book/cart.html', {
        'cart_items': cart_items,
    })

def cart_delete(request, slug):
    cart_items = request.session.get('cart_items') or []

    for i in range(len(cart_items)):
        if cart_items[i]['slug'] == slug:
            del cart_items[i]
            break
    
    request.session['cart_items'] = cart_items
    return HttpResponseRedirect(reverse('book:cart_list', kwargs={}))

from django.core.mail import EmailMessage

def cart_checkout(request):
    subject = 'Test mail' 
    body = '''
        <p>This is a test mail message</p>
    '''
    email = EmailMessage(subject=subject, body=body, to=['photographyref@gmail.com'])
    email.content_subtype = 'html'
    email.send()

    return HttpResponseRedirect(reverse('book:index', kwargs={}))

testproject/templates/book/add.html
{% extends 'layouts/base.html' %} 
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %} Book Detail {% endblock %} 

{% block content %}


<div class="row mb-5">
    <div class="col-lg-6 offset-lg-3">
        
        <h1 class="display-6">Book Add</h1>
        <form method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Save book</button>
        </form>
    </div>
</div>



{% endblock  %}

testproject/templates/book/cart.html
{% extends 'layouts/base.html' %} 
{% load humanize %}

{% block title %} Shopping Cart {% endblock %} 

{% block content %}



<div class="container px-4">
    <div class="row gx-5">

        <div class="col">

            <div class="col-lg-6 offset-lg-3 ">
                <h1>Cart List</h1>
            
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Qty</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in cart_items %}
                        <tr>
                            <td>{{ c.name }}</td>
                            <td>{{ c.qty }}</td>
                            <td>¥ {{ c.price|floatformat:0|intcomma }}</td>
                            <td>
                                <a href="{% url 'book:cart_delete' slug=c.slug %}">Delete item</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'book:cart_checkout' %}" class="btn btn-primary btn-make_list float-md-end">
                    Process checkout <i class="fa fa-chevron-right"></i>
                </a>
            </div>
        
        </div>
    
    </div>

</div>

{% endblock content %}

testproject/templates/book/detail.html
{% extends 'layouts/base.html' %} 
{% load humanize %}

{% block title %} Book Detail {% endblock %} 

{% block content %}

<div class="container-fluid">

    <div class="row ">
        <div class="py-4 col-lg-2">
            {% if book.image %}
            <img src="{{ book.image.url }}" alt="" class="img-fluid mb-4">
            {% endif %}
        </div>
        <div class="py-4 px-4 col-lg-10">
            <h2>{{ book.name }}</h2>
            <div>Category : {{ book.category }}</div>
            <div>Price : ¥{{ book.price|floatformat:0|intcomma }}</div>
            <a href=" {% url 'book:cart_add' slug=book.slug %} " class="btn btn-success mt-5">Add to Cart</a>
        </div>

        <h5>Comment ( {{ book.get_comment_count }} ) </h5>
        {% for c in book.bookcomment_set.all %}
        <div class="card mb-4">
            <div class="card-body">
                <p>"{{ c.comment }}"</p>
                <div>Rating: {{ c.rating }}</div>
            </div>
        </div>
        {% endfor %}

    </div>
    <a href="{% url 'book:index' %}" class="mt-4">Back to previous page</a>
</div>

{% endblock  %}

testproject/templates/book/index.html
{% extends 'layouts/base.html' %} 
{% load humanize %}

{% block title %} Book Page {% endblock %} 


{% block content %}

<h1>Book List</h1>
<a href="{% url 'book:book_add' %}" class="btn btn-success">Add new book</a>
<hr>
<div class="row">
  
  <!-- left Category block -->
  
  <div class="col-lg-2">
  
    <div class="list-group">
      <a href="{% url 'book:index' %}"
        class="list-group-item list-group-item-action {% if not catege_id %} active {% endif %}" aria-current="true">All</a>
  
      {% for c in categories %}
      <a href="{% url 'book:index' %}?categoryid={{ c.id }}"
        class="list-group-item list-group-item-action {% if catege_id|add:"0" == c.id %}active{% endif %}">{{ c.name }}</a>
      {% endfor %}
    </div>
  </div>
  <!-- End Category block -->
  
  <div class="col-lg-10">

    <div class="row">
      {% for b in books %}
      <div class="col-lg-3">
        <div class="card mb-4">
            
            {% if b.image %}
            <a href="{% url 'book:detail' slug=b.slug %}">
                <img src="{{ b.image.url }}" alt="" class="card-img-top" />
            </a>
            {% endif %}

          <div class="card-body">
            <h5><a href="{% url 'book:detail' slug=b.slug %}"> {{ b.name }} </a></h5>
            <div>Category: {{ b.category.name }}</div>
            <div>Price: ¥ {{ b.price|floatformat:0|intcomma }}</div>
            <div>Author:</div>
            {% for a in b.author.all  %}
            <span class="badge bg-secondary">{{ a.name }}</span>
            {% endfor %}
            <br>
            <a href="{% url 'book:detail' slug=b.slug %}" 
              class="btn btn-outline-info mt-4">View detail</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=page_obj.previous_page_number">Previous</a></li>
      {% endif %}
      
      {% for i in page_obj.paginator.page_range %}
        <li class="page-item {% if books.number == i %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endfor %}
      
      {% if page_obj.has_next %} 
        <li class="page-item"><a class="page-link" href="?page=page_obj.next_page_number">Next</a></li>
      {% endif %}

    </ul>

  </div>
</div>

{% endblock %}