testproject/book/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', login_required(views.BookListView.as_view(), login_url='/login'), name='index'),
    # path('detail<slug:slug>/', views.detail, name='detail'),
    path('detail<slug:slug>/', views.BookDetailView.as_view(), name='detail'),
    re_path(r'add/$', views.book_add, name='book_add'),
    
    re_path(r'cart/add/(?P<slug>[\w-]+)/$', views.cart_add, name='cart_add'),
    re_path(r'cart/delete/(?P<slug>[\w-]+)/$', views.cart_delete, name='cart_delete'),
    re_path(r'cart/list/$', views.cart_list, name='cart_list'),
    re_path(r'cart/checkout/$', views.cart_checkout, name='cart_checkout'),
]
  

testproject/myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from book.api import router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
    path('book/', include(('book.urls', 'book'), namespace='book')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/templates/layouts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <title> {% block title %} Test Project {% endblock %}</title>
  </head>
  <body>
        <!--  Navbar -->
    <nav class="py-4 bg-body-tertiary border-bottom">
      <div class="container d-flex flex-wrap container-fluid">
        <ul class="nav me-auto">
          <li class="nav-item"><a href="{% url 'myapp:index' %}" class="nav-link link-body-emphasis px-2 active" aria-current="page">THE BOOKSTAND..</a></li>
          <li class="nav-item"><a href="{% url 'book:index' %}" class="nav-link link-body-emphasis px-2">BookStore</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">About</a></li>
          <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">FAQs</a></li>
        </ul>
        <ul class="nav">
          {% if request.session.cart_qty %}
          <li class="nav-item"><a href="{% url 'book:cart_list' %}" class="btn btn-outline-primary me-4" ><i class="fa fa-shopping-cart"></i> {{ request.session.cart_qty }}</a>
          </li>
          {% endif %}

          {% if not user.is_authenticated %} 
          <li class="nav-item"><a href="{% url 'myapp:login' %}" class="btn btn-outline-primary me-4">Login</a></li>
          <li class="nav-item"><a href="#" class="btn btn-primary me-4">Sign In </a></li>
          {% endif %}

          {% if user.is_authenticated %}
          <p class="me-2 text-success"><em>Hello,&nbsp{{ request.user.username }}</em></p>
          <form method="post" action="{% url 'myapp:logout' %}" novalidate>
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger mx-2">Log out</button>
          </form>
          {% endif %}  
        </ul>
      </div>
    </nav> 

    <!-- end Navbar -->


    <div class="container">
      {% if messages %}
        {% for msg in messages %}
      
      {% if msg.tags == 'success' %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success</strong> {{ msg }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
      
      {% if msg.tags == 'error' %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error</strong> {{ msg }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
      
        {% endfor %}
      {% endif %}

      {% block content %}
      
      {% endblock  %}
        
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <!-- <footer class="footer mb-4 py-4">
        <div class="container">
        <ul class="nav justify-content-center">
          <li class="nav-item"><a href="{% url 'myapp:index' %}" class="nav-link px-2 text-muted" aria-current="page">Home</a></li>
          <li class="nav-item"><a href="{% url 'book:index' %}" class="nav-link px-2 text-muted">BookStore</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"">About</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        </ul>
        <p class="text-center text-muted">&copy Copyright: 2023 The Book Stand Company, Inc</p>
      </div>
      </footer> -->

      
      <div class="position-sticky">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
          <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
              <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">&copy;Copyright 2023 The Book Stand Company, Inc</span>
          </div>
      
          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
          </ul>
        </footer>
      </div>

  </body>
</html>



<!-- <div class="container-fluid">    
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="{% url 'myapp:index' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      {% comment %} <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg> {% endcomment %}
      <span class="fs-5">The Book Stand</span>
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="{% url 'book:index' %}" class="nav-link px-2 link-dark">BookStore</a></li>
      <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
    </ul>

    <div class="col-md-3 text-end">
      {% if request.session.cart_qty %}
      <a class="btn btn-outline-primary me-2" href="{% url 'book:cart_list' %}"><i class="fa fa-shopping-cart"></i> {{ request.session.cart_qty }}</a>
      {% endif %}

      
      {% if not user.is_authenticated %} 
      <a class="btn btn-primary" href="#">Sign-up</a>
      <a class="btn btn-outline-primary me-2" href="{% url 'myapp:login' %}">Login</a>
      {% endif %}
      
      
      {% if user.is_authenticated %}
        <span>Hello, {{ request.user.username }}</span>
        <form method="post" action="{% url 'myapp:logout' %}" novalidate>
          {% csrf_token %}
          <button type="submit" class="btn btn-danger mx-2">Log out</button>
        </form>
      {% endif %}       
    </div>
  </header>
</div> -->


 